---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: node_exporter
  register: _node_exporter_tempdir
  check_mode: false
  changed_when: false

- name: "Create release folder for v{{ node_exporter_version }}"
  ansible.builtin.file:
    path: "{{ node_exporter_release_path }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "{{ node_exporter_directories_permissions }}"
  notify:
    - "update symlink"

- name: "Download Node Exporter v{{ node_exporter_version }}"
  ansible.builtin.get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "{{ _node_exporter_tempdir.path }}/{{ node_exporter_archive_name }}"
    checksum: "{{ node_exporter_archive_checksum }}"
    mode: "{{ node_exporter_files_permissions }}"
  check_mode: false
  changed_when: false

- name: "Unarchive Node Exporter into '{{ node_exporter_release_path }}'"
  ansible.builtin.unarchive:
    src: "{{ _node_exporter_tempdir.path }}/{{ node_exporter_archive_name }}"
    dest: "{{ node_exporter_release_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    extra_opts:
      - "--strip-components=1"
      - "--show-stored-names"
      - "--wildcards"
    remote_src: true
  notify:
    - "update symlink"

- name: Install Node Exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/{{ node_exporter_service_name }}.service"
    mode: "0644"
  notify:
    - "restart node_exporter"
...
