{
 "title": "✈️Airline Manager",
 "tags": [
  "Prometheus",
  "AirlineManager",
  "applications"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "GROUP_INTERVAL",
    "label": "Group interval",
    "query": "5m,10m,30m,1h,3h,6h,12h,24h,2d,4d,7d"
   }
  ]
 },
 "panels": [
  {
   "title": "📈Share price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "am4_company_share_value > 0", "legendFormat": "USD" }
   ]
  },
  {
   "title": "🏆Company rank",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "am4_company_rank > 0", "legendFormat": "rank" }
   ]
  },
  {
   "title": "⭐Company reputation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (am4_company_reputation)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "🛬Fleet status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "am4_ac_hangar_capacity", "legendFormat": "capacity" },
    { "expr": "am4_ac_fleet_size", "legendFormat": "size" },
    { "expr": "am4_ac_routes", "legendFormat": "routes" },
    {
     "expr": "am4_ac_status{type=\"wo_route\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "am4_ac_status{type=\"in_flight\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "am4_ac_status{type=\"pending_delivery\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "am4_ac_status{type=\"pending_maintenance\"}",
     "legendFormat": "{{type}}"
    },
    { "expr": "am4_company_training_points", "legendFormat": "training points" }
   ]
  },
  {
   "title": "📊Company stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "am4_stats_flights_operated", "legendFormat": "✈️flights" },
    {
     "expr": "am4_stats_passengers_transported{type=\"first\"}",
     "legendFormat": "🎫PAX {{type}}"
    },
    {
     "expr": "am4_stats_passengers_transported{type=\"business\"}",
     "legendFormat": "🎟️PAX {{type}}"
    },
    {
     "expr": "am4_stats_passengers_transported{type=\"economy\"}",
     "legendFormat": "💳PAX {{type}}"
    },
    {
     "expr": "am4_stats_cargo_transported{type=\"large\"}",
     "legendFormat": "📒cargo {{type}}"
    },
    {
     "expr": "am4_stats_cargo_transported{type=\"heavy\"}",
     "legendFormat": "📕cargo {{type}}"
    }
   ]
  },
  {
   "title": "💲Account money change",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(type) (am4_company_money{type=\"Airline account\"}) > 0",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "⛽Fuel capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(type) (avg_over_time(am4_company_fuel_holding[$__interval])) * 100) / sum by(type) (am4_company_fuel_limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⛽Fuel price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "expr": "sum by(type) (am4_market_fuel_price) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "✈️Flights departed per ${GROUP_INTERVAL}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "changes(am4_stats_flights_operated[$__interval])",
     "legendFormat": "✈️flights"
    }
   ]
  },
  {
   "title": "💺PAX transported by class per ${GROUP_INTERVAL}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(type) (delta(am4_stats_passengers_transported[$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "📦Cargo transported per ${GROUP_INTERVAL}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "expr": "sum by(type) (delta(am4_stats_cargo_transported[$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "🛬Hubs",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "am4_hub_stats{type=\"arrivals\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "am4_hub_stats{type=\"departures\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "am4_hub_stats{type=\"paxArrived\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "am4_hub_stats{type=\"paxDeparted\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "📦Cargo transported total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "expr": "sum by(type) (avg_over_time(am4_stats_cargo_transported[$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Alliance stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "⭐Contributed per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "am4_alliance_contributed_per_day > 0",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "⭐Contributed total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "am4_alliance_contributed_total > 0",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "⭐Season",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "am4_alliance_season_money > 0", "legendFormat": "USD" }
   ]
  }
 ]
}