{
 "title": "Cardinality Explorer",
 "description": "Find cardinality sources",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "query_result( count by (job)(up{}) )"
   },
   {
    "name": "metric",
    "query": "query_result( count by (__name__) ({job=\"$job\" }) )"
   },
   {
    "name": "labels",
    "query": "query_result(topk(32,$metric{job=\"$job\"} ) )"
   },
   {
    "name": "label_names",
    "query": "query_result(topk(32,$metric{job=\"$job\"} ) )"
   }
  ]
 },
 "panels": [
  { "title": "how to", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How To",
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Cardinality Explorer\n[Cardinality](https://www.robustperception.io/cardinality-is-key) is the count at a certain time of the total unique combinations of keys and labels.  Too much (red) is bad, and will make your queries slow and your prometheus run out of memory.  This dashboard will help you analyze individual metrics to determine the cause(s) of cardinality.\n## WARNING\n * This dashboard can be *very* slow and heavy\n * Use with caution\n\n## Instructions\n 1. Choose the datasource which contains your data from the `datasource` dropdown\n 2. Choose a job from the `job` dropdown, which is now populated with the prometheus jobs in your account\n 3. Choose a metric name from the `metric` dropdown, now populated with with the metrics available to the specified job in your account\n 4. Choose the `labels` which you would like to run calculations on\n\n## Understanding the Data\n * The `(metricname) cardinality` row gives you basic information about your metric\n    * The `metric` panel shows the metric name you've chosen\n    * The `cardinality` panel shows the metric's cardinality\n * The `count by label` row shows the number of unique values for every label\n * The `cardinality calculation` row shows information based on the labels you selected in the `labels` dropdown\n    * The `count without()` panel shows what the cardinality of the metric would be if the specified labels were to be removed\n    * The `count by()` panel shows what the cardinality of the specified labels as a group is"
   }
  },
  { "title": "$metric cardinality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "metric",
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 16 },
   "options": {
    "content": "<center><h1 style=\"color:#2980B9;\">$metric</h1></center>"
   }
  },
  {
   "title": "cardinality",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( $metric{job=\"$job\"}) "
    }
   ]
  },
  { "title": "count by label", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "${label_names}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "repeat": "label_names",
   "targets": [
    {
     "expr": "count(count by (${label_names})( $metric{job=\"$job\"}) )"
    }
   ]
  },
  { "title": "cardinality calculation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "count without (${labels:csv})",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count without (${labels:csv})( $metric{job=\"$job\"}) )"
    }
   ]
  },
  {
   "title": "count by (${labels:csv})",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (${labels:csv})( $metric{job=\"$job\"}) )"
    }
   ]
  },
  { "title": "faq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "title": "Frequently Asked Questions", "type": "text", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 } }
 ]
}