{
 "title": "JVM metrics",
 "description": "Dashboard for JVM metrics within Kubernetes, where Prometheus installed using community helm chart",
 "tags": [
  "jvm_exporter",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_runtime_info,instance)"
    }
   },
   {
    "name": "jvm_pool",
    "query": {
     "query": "label_values(jvm_memory_pool_max_bytes{pool!~\"^CodeHeap.+\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_runtime_info{instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory area",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used {{ area }}"
    }
   ]
  },
  {
   "title": "$jvm_pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "repeat": "jvm_pool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{instance=\"$instance\",pool=\"$jvm_pool\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{instance=\"$instance\",pool=\"$jvm_pool\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{instance=\"$instance\",pool=\"$jvm_pool\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{instance=\"$instance\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "jvm_classes_unloaded_total{instance=\"$instance\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "Threads ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads State",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=\"$instance\",state=\"RUNNABLE\"}",
       "legendFormat": "{{ state }}"
      },
      {
       "expr": "jvm_threads_state{instance=\"$instance\",state=\"BLOCKED\"}",
       "legendFormat": "{{ state }}"
      },
      {
       "expr": "jvm_threads_state{instance=\"$instance\",state=\"NEW\"}",
       "legendFormat": "{{ state }}"
      },
      {
       "expr": "jvm_threads_state{instance=\"$instance\",state=\"TERMINATED\"}",
       "legendFormat": "{{ state }}"
      },
      {
       "expr": "jvm_threads_state{instance=\"$instance\",state=\"TIMED_WAITING\"}",
       "legendFormat": "{{ state }}"
      },
      {
       "expr": "jvm_threads_state{instance=\"$instance\",state=\"WAITING\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{instance=\"$instance\"}",
       "legendFormat": "JVM current threads"
      },
      {
       "expr": "jvm_threads_daemon{instance=\"$instance\"}",
       "legendFormat": "JVM daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{instance=\"$instance\"}",
       "legendFormat": "JVM deadlocked threads"
      }
     ]
    }
   ]
  }
 ]
}