{
 "title": "🌐Speedtest",
 "description": "Speedtest metrics",
 "tags": [
  "speedtest_exporter",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   {
    "name": "ISP",
    "label": "ISP",
    "query": {
     "query": "label_values(speedtest_latency_seconds, user_isp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "↕️Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(speedtest_download_speed_Bps{user_isp=\"$ISP\"}[$__interval]))",
     "legendFormat": "⏬Download"
    },
    {
     "expr": "sum(avg_over_time(speedtest_upload_speed_Bps{user_isp=\"$ISP\"}[$__interval]))",
     "legendFormat": "⏫Upload"
    }
   ]
  },
  {
   "title": "⏬Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download_speed_Bps{user_isp=\"$ISP\"}[1w:10m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_download_speed_Bps{user_isp=\"$ISP\"}[1w:10m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_download_speed_Bps[1w:10m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "⏫Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload_speed_Bps{user_isp=\"$ISP\"}[1w:10m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_upload_speed_Bps{user_isp=\"$ISP\"}[1w:10m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_upload_speed_Bps[1w:10m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "🐢Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_latency_seconds{user_isp=\"$ISP\"}[1w:10m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_latency_seconds{user_isp=\"$ISP\"}[1w:10m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_latency_seconds[1w:10m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "🐢Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(speedtest_latency_seconds{user_isp=\"$ISP\"}[$__interval]))",
     "legendFormat": "🐢Latency"
    }
   ]
  },
  {
   "title": "⏱️Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(speedtest_scrape_duration_seconds[$__interval]))",
     "legendFormat": "⏱️Duration"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "speedtest_download_speed_Bps" },
    { "expr": "speedtest_upload_speed_Bps" },
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  }
 ]
}