---
# handlers file for alertmanager
- name: Stop Prometheus
  ansible.builtin.systemd_service:
    name: "{{ alertmanager_service_name }}"
    daemon_reload: true
    enabled: true
    force: true
    state: stopped
  listen:
    - "restart alertmanager"
    - "update symlink"

- name: Update symlink
  ansible.builtin.file:
    src: "{{ alertmanager_release_path }}"
    path: "{{ alertmanager_releases_path }}/current"
    state: link
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
  listen:
    - "update symlink"

- name: Start Prometheus
  ansible.builtin.systemd_service:
    name: "{{ alertmanager_service_name }}"
    daemon_reload: true
    enabled: true
    force: true
    state: started
  listen:
    - "restart alertmanager"
    - "update symlink"

- name: Reload Prometheus
  ansible.builtin.systemd_service:
    name: "{{ alertmanager_service_name }}"
    state: reloaded
  listen:
    - "reload alertmanager"
...
