---
# handlers file for grafana
- name: Stop Grafana
  ansible.builtin.systemd_service:
    name: "{{ grafana_service_name }}"
    daemon_reload: true
    enabled: true
    force: true
    state: stopped
  listen:
    - "restart grafana"
    - "stop grafana"

- name: Start Grafana
  ansible.builtin.systemd_service:
    name: "{{ grafana_service_name }}"
    daemon_reload: true
    enabled: true
    force: true
    state: started
  listen:
    - "restart grafana"
    - "start grafana"

- name: "Waiting for start Grafana on {{ '{}:{}'.format(grafana_config.server.http_addr, grafana_config.server.http_port) }}"
  ansible.builtin.wait_for:
    host: "{{ grafana_config.server.http_addr }}"
    port: "{{ grafana_config.server.http_port }}"
    delay: 5
    timeout: 60
  listen:
    - "restart grafana"
    - "start grafana"
...
