---
- name: Create Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_conf_path }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "{{ prometheus_files_permissions }}"
  notify:
    - "restart prometheus"

- name: Create Prometheus alert rules
  ansible.builtin.copy:
    src: files/alert_rules/
    dest: "{{ prometheus_alert_rules_path }}/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "{{ prometheus_files_permissions }}"
  notify:
    - "reload prometheus"
...
