---
# Non-default variables for Prometheus hosts
# Example: override Prometheus configuration to add scrape jobs for Alertmanager, Node Exporter, Grafana, and HAProxy Exporter
prometheus_web_external_url: "https://mymonitoring.example.com/prometheus/"

prometheus_config:
  global:
    scrape_interval: 10s

  alerting:
    alertmanagers:
      - path_prefix: "/alertmanager/"
        static_configs:
          - targets:
              - "{{ alertmanager_web_listen_address }}"

  rule_files:
    - "{{ prometheus_alert_rules_path }}/*"

  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/prometheus/metrics"
      static_configs:
        - targets: ["{{ prometheus_web_listen_address }}"]

    - job_name: "alertmanager"
      metrics_path: "/alertmanager/metrics"
      static_configs:
        - targets: ["{{ alertmanager_web_listen_address }}"]

    - job_name: "node"
      static_configs:
        - targets: ["{{ node_exporter_web_listen_address }}"]

    - job_name: "grafana"
      metrics_path: "/grafana/metrics"
      static_configs:
        - targets: ["{{ grafana_web_listen_address }}"]
      basic_auth:
        username: "{{ grafana_basic_auth.username }}"
        password: "{{ grafana_basic_auth.password }}"

    - job_name: "haproxy"
      static_configs:
        - targets: ["{{ haproxy_exporter_listen_address }}"]
...
